databases:
  - name: flowervase1_DB
    databaseName: flowervase1_db
    user: flowervase
    region: singapore

services:
  - type: web
    name: flowervase
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: flowervase_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false